name: Hello Workd on App Engine
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Hello World
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Deploy App Engine
        uses: claudiuri/deploy-gae-action@v1.2

